name: Execucao Manual

on:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install  # Instala as dependências do projeto

      - name: Run Cypress Tests
        run: npx cypress run  # Executa os testes do Cypress