name: Execucao Manual

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Instalando as dependencias
        run: npm install  # Instala as dependências do projeto

      - name: Executando os testes
        run: npx cypress run  # Executa os testes do Cypress

      - name: Obtendo o report dos testes
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./cypress/reports/**